name: CI
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.25", "1.26", "1.27"]
    container:
      image: golang:${{ matrix.go-version }}-trixie

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: null_test
          POSTGRES_USER: null_test
          POSTGRES_PASSWORD: temba
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run tests
        run: go test -p=1 -coverprofile=coverage.text -covermode=atomic ./...

  test-all:
    name: Test
    needs: [test]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check all matrix legs passed
        run: test "${{ needs.test.result }}" = "success"
