name: CI
on: [push, pull_request]
jobs:
  test:
    name: Test
    env:
      pg-version: "14"
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: ${{ env.pg-version }}
          postgresql db: null_test
          postgresql user: nyaruka
          postgresql password: nyaruka

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests
        run: go test -p=1 -coverprofile=coverage.text -covermode=atomic ./...

      - name: Upload coverage
        if: success()
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
